---
services:
  authentik:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_TAG:-2026.5.0}
    container_name: authentik-server
    command: server
    env_file:
      - "${BAK_CFG_DIR}/authentik/.env"
    labels:
      - traefik.enable=true
      - traefik.http.services.authentik.loadbalancer.server.port=9000
      - traefik.http.routers.authentik.rule=Host(`authentik.${CF_DOMAIN}`) || HostRegexp(`{subdomain:[A-Za-z0-9](?:[A-Za-z0-9\-]{0,61}[A-Za-z0-9])?}.${CF_DOMAIN}`) && PathPrefix(`/outpost.goauthentik.io/`)
    volumes:
      - "${BAK_CFG_DIR}/authentik/authentik_server-media:/media"
      - "${BAK_CFG_DIR}/authentik/authentik-server-data:/data"
      - "${BAK_CFG_DIR}/authentik/authentik_server_custom-templates:/templates"
    depends_on:
      - authentik-db
      - authentik-redis
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - ${COMPOSE_PORT_HTTP:-9000}:9000
      - ${COMPOSE_PORT_HTTPS:-9443}:9443
    shm_size: 512mb


  authentik-worker:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_TAG:-2026.5.0}
    container_name: authentik-worker
    command: worker
    env_file:
      - "${BAK_CFG_DIR}/authentik/.env"
    user: root
    volumes:
      - /run/docker.sock:/run/docker.sock
      - "${BAK_CFG_DIR}/authentik/authentik_worker-media:/media"
      - "${BAK_CFG_DIR}/authentik/authentik_worker-certs:/certs"
      - "${BAK_CFG_DIR}/authentik/authentik-worker-data:/data"
      - "${BAK_CFG_DIR}/authentik/authentik_worker_custom-templates:/templates"
    depends_on:
      - authentik-db
      - authentik-redis
    restart: unless-stopped
    networks:
      - proxy
    shm_size: 512mb

  authentik-redis:
    image: docker.io/library/redis:latest
    container_name: authentik-redis
    command: --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - authentik_redis:/data
    restart: unless-stopped
    networks:
      - proxy

  authentik-db:
    image: docker.io/library/postgres:16-alpine
    container_name: authentik-db
    env_file:
      - "${BAK_CFG_DIR}/authentik/.env"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 5
    volumes:
      - authentik_postgres:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  authentik_postgres:
    driver: local
  authentik_redis:
    driver: local
