---
services:
  uptime:
    image: louislam/uptime-kuma:2
    container_name: uptime
    networks:
      - proxy # rename this to your custom docker network
    labels:
      traefik.enable: true
      # public status page
      # traefik.http.routers.uptime-status.rule: Host(`status.hudater.dev`) || Host(`status.${CF_DOMAIN}`)
      traefik.http.routers.uptime-status.rule: Host(`status.hudater.dev`)
      traefik.http.routers.uptime-status.entrypoints: https
      traefik.http.routers.uptime-status.tls: true
      # admin dash
      traefik.http.routers.uptime-admin.rule: Host(`uptime.${CF_DOMAIN}`)
      traefik.http.routers.uptime-admin.entrypoints: https
      traefik.http.routers.uptime-admin.tls: true
      traefik.http.routers.uptime-admin.middlewares: oauth@file
    volumes:
      - "${CFG_DIR}/uptime:/app/data"
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 3001:3001
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

networks:
  proxy:    # rename this to your custom docker network.
    external: true
